// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBoVMYwrdQrgPla7290IY5Rx746g9uTDoU',
    appId: '1:427010099137:web:bde84d6744dc24b7c21140',
    messagingSenderId: '427010099137',
    projectId: 'novafitapp-9e463',
    authDomain: 'novafitapp-9e463.firebaseapp.com',
    storageBucket: 'novafitapp-9e463.firebasestorage.app',
    measurementId: 'G-02FSLBYJZ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpFAqRHjzeX0FXjY9JpptDr97H7hR6nQE',
    appId: '1:427010099137:android:01a66794f5874bb2c21140',
    messagingSenderId: '427010099137',
    projectId: 'novafitapp-9e463',
    storageBucket: 'novafitapp-9e463.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL0eSgiq04EWCNV0xrJWmRqGVAVldhjt8',
    appId: '1:427010099137:ios:e1ccaa281c870392c21140',
    messagingSenderId: '427010099137',
    projectId: 'novafitapp-9e463',
    storageBucket: 'novafitapp-9e463.firebasestorage.app',
    iosBundleId: 'com.example.novafitGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL0eSgiq04EWCNV0xrJWmRqGVAVldhjt8',
    appId: '1:427010099137:ios:e1ccaa281c870392c21140',
    messagingSenderId: '427010099137',
    projectId: 'novafitapp-9e463',
    storageBucket: 'novafitapp-9e463.firebasestorage.app',
    iosBundleId: 'com.example.novafitGym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBoVMYwrdQrgPla7290IY5Rx746g9uTDoU',
    appId: '1:427010099137:web:aef475d1fea62118c21140',
    messagingSenderId: '427010099137',
    projectId: 'novafitapp-9e463',
    authDomain: 'novafitapp-9e463.firebaseapp.com',
    storageBucket: 'novafitapp-9e463.firebasestorage.app',
    measurementId: 'G-HQY675F1XN',
  );
}
